### ISSUE TITLE
Vaultage V2

### ISSUE THREAD

**Issue by stephpy** [rezzza/vaultage#27]
Hi,

I need to implement some new features that vaultage does not provide at this moment.
I could make a PR to add them but I would like to know if you are agree to merge them before.

Needs:

# Multi catalogs

V1: we cannot have different backend for 2 files crypted with vaultage
V2: we can define catalogs and have a better granularity of user rights.

# --write replaced by ! --dry-run

V1: --write to encrypt/decrypt ...
V2: --dry-run to not encrypt/decrypt ;) looks a better UX.

I have some other ideas which could be done in v2.x (wildcard filepaths, ...) but the Multi Catalog feature would be BC break.

Here is an example of the multi-catalog feature:

```
#.vaultage.yaml

catalogs:
    dev:
        backend:
            type: basic
            key: "file:///tmp/pouet.key"
            passphrase: false,
            encrypted_extension: "crypted",
        files: 
            - "app/config/parameters/dev.yml"
    preprod:
        backend:
          type: gpg
          asymetric: false
        files:
            - "app/config/parameters/preprod.yml"
    prod:
        backend:
          type: gpg
          asymetric: true
          recipients:
            - "John Doe <user@domain.tld>"
        files:
            - "app/config/parameters/prod.yml"
```

we have to choose a format ... this one is not bad too.

```
files:
  app/config/parameters/dev.yml:     dev
  app/config/parameters/preprod.yml: preprod
  app/config/parameters/prod.yml:    prod
backend:
    dev:
        basic:
            key: "file:///tmp/pouet.key"
            passphrase: false,
            encrypted_extension: "crypted",
    preprod:
        gpg:
          asymetric: false
    prod:
        gpg:
          asymetric: true
          recipients:
            - "John Doe <user@domain.tld>"
```

Thoughts ?
